# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

# Setup
title:            Matej Troják
tagline:          'Homepage'
description:      'Planetary Biology Biocurator at <a href="https://www.embl.org/">EMBL</a>'
url:
#baseurl:          /

author:
  name:           'Matej Troják'
  url:

github:
  repo:         xtrojak

# Custom vars
version:
remote_theme: fongandrew/hydeout
